### ISSUE TITLE
Extractor not working for me in CSE Nightly 2015-12-02

### ISSUE THREAD

**Issue by tormoseng** [CloudScale-Project/Environment#7]
I get the error: "Please, check your discoverer and SoMoX configuration. SoMoX Failed".

I re-run the same case (same project and configurations) on the CSE 3.2 release, and here it works good.

**Comment by jurepolutnik** [comment]
Could be that something has changed on SoMoX side (we are also grabbing all tools' changes). Will check.

**Comment by jurepolutnik** [comment]
Extractor (Somox) has been updated on 1.12.
Somthing changed in org.somox.kdmhelper.KDMReader.loadFile()

Will see if that can be fixed on our side, otherwise Somox needs to be fixed.  

---

eclipse.buildId=unknown
java.version=1.7.0_65
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -clearPersistedState
Command-line arguments:  -os linux -ws gtk -arch x86_64 -clearPersistedState

org.apache.log4j
Error
Thu Dec 03 11:07:58 CET 2015
org.somox.analyzer.simplemodelanalyzer.SimpleModelAnalyzer  - Failed to load GAST Model

java.io.FileNotFoundException: /Minimal-Example/Extractor/Results/Alternative_2015-12-03_11-07-58/modisco/Minimal-Project_java2kdm.xmi (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at org.eclipse.emf.ecore.resource.impl.FileURIHandlerImpl.createInputStream(FileURIHandlerImpl.java:99)
    at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360)
    at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1269)
    at org.somox.kdmhelper.KDMReader.loadFile(KDMReader.java:92)
    at org.somox.analyzer.simplemodelanalyzer.SimpleModelAnalyzer.analyze(SimpleModelAnalyzer.java:91)
    at org.somox.core.impl.SoMoXCoreStandard.runAnalyzer(SoMoXCoreStandard.java:100)
    at org.somox.ui.GUISoMoXCoreController.startAnalyze(GUISoMoXCoreController.java:76)
    at org.somox.analyzer.simplemodelanalyzer.jobs.SimpleModelAnalyzerJob.execute(SimpleModelAnalyzerJob.java:93)
    at eu.cloudscaleproject.env.extractor.util.ExtractorRunJob.runSomox(ExtractorRunJob.java:166)
    at eu.cloudscaleproject.env.extractor.util.ExtractorRunJob.run(ExtractorRunJob.java:77)
    at eu.cloudscaleproject.env.extractor.alternatives.ConfingAlternative.doRun(ConfingAlternative.java:57)
    at eu.cloudscaleproject.env.toolchain.resources.types.AbstractConfigAlternative$1.run(AbstractConfigAlternative.java:99)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2225)
    at eu.cloudscaleproject.env.toolchain.resources.types.AbstractConfigAlternative.run(AbstractConfigAlternative.java:96)
    at eu.cloudscaleproject.env.toolchain.ui.ConfigEditorView$AlternativeRunJob.run(ConfigEditorView.java:407)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by jurepolutnik** [comment]
Falko is the bad guy... Will fix our side.
This is why nightly can be broken sometimes...

https://svnserver.informatik.kit.edu/i43/svn/code/SoMoX/Core/trunk/org.somox.analyzer.sissymodelanalyzer/src/org/somox/analyzer/simplemodelanalyzer/SimpleModelAnalyzer.java
....
        /*\* Changed by Falko Hansch*/
        final URI fileURI = URI.createFileURI(platformPath);

**Comment by jurepolutnik** [comment]
Fixed.

**Comment by snowball77** [comment]
Great, thx
